before_install:
  - bash download_serf
  - bundle install --path .bundle
rvm:
  - 2.0.0
  - 2.3
branches:
  only:
    - master
script: "bundle exec rake spec"
addons:
  code_climate:
    repo_token: 894a7a896e5ac4a4e7e497051fbc68152f348989a5b930cc3a037c713cf63df0 
